/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetinhoVoltando;

import org.junit.Test;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
        assertThat(1, is(2));

    }
}
